### ISSUE TITLE
Example running error, requesting help, thank you

### ISSUE THREAD

**Issue by aa584521** [DenisLAD/twain4java#2]
Example running error, requesting help, thank you！

Connected to the target VM, address: '127.0.0.1:56702', transport: 'socket'
Metal
Nimbus
CDE/Motif
Windows
TWAIN GET: 0f10ffff000000000000000000000000,0f10040070df8e694901000000000000,TWAIN GET: 1811ffff000000000000000000000000,18110400b020ce694901000000000000,java.lang.NullPointerException
	at free.lucifer.jtwain.TwainCapability.dumpHex(TwainCapability.java:142)
	at free.lucifer.jtwain.TwainCapability.get(TwainCapability.java:87)
	at free.lucifer.jtwain.TwainCapability.get(TwainCapability.java:105)
	at free.lucifer.jtwain.TwainCapability.get(TwainCapability.java:109)
	at free.lucifer.jtwain.TwainCapability.<init>(TwainCapability.java:45)
	at free.lucifer.jtwain.TwainSource.getCapability(TwainSource.java:196)
	at free.lucifer.jtwain.ui.ScannerFrame.selectScannerActionPerformed(ScannerFrame.java:258)
	at free.lucifer.jtwain.ui.ScannerFrame.access$100(ScannerFrame.java:51)
	at free.lucifer.jtwain.ui.ScannerFrame$2.actionPerformed(ScannerFrame.java:108)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DenisLAD** [comment]
Can you provide additional information?

Scanner vendor: HP, Canon, ...

JVM Version: JDK? 32 or 64 bits VM?

Windows version: ?

**Comment by DenisLAD** [comment]
Try to check. Did some fix NPE error
https://github.com/DenisLAD/twain4java/pull/5

**Comment by DenisLAD** [comment]
No activity
