### ISSUE TITLE
Get Twain Container NullPointerException

### ISSUE THREAD

**Issue by hongsonvx1** [DenisLAD/twain4java#4]
Hello, i included twain lib to my spring boot project. But i give a error NullPointerException

Can you tell me how to fix this error?

My system info:
OS: Windows 11 x64
Java version: 17 x64

Log:
TWAIN GET: 0f10ffff000000000000000000000000,0f10050080b0c9fc1302000000000000,TWAIN GET: 0b10ffff000000000000000000000000,0b10050050b1c9fc1302000000000000,java.lang.NullPointerException: Cannot read the array length because "bytes" is null
	at free.lucifer.jtwain.TwainCapability.dumpHex(TwainCapability.java:142)
	at free.lucifer.jtwain.TwainCapability.get(TwainCapability.java:87)
	at free.lucifer.jtwain.TwainCapability.get(TwainCapability.java:105)
	at free.lucifer.jtwain.TwainCapability.getCurrent(TwainCapability.java:113)
	at free.lucifer.jtwain.TwainCapability.<init>(TwainCapability.java:53)
	at free.lucifer.jtwain.TwainSource.getCapability(TwainSource.java:200)
	at free.lucifer.jtwain.TwainSource.setCapability(TwainSource.java:223)
	at free.lucifer.jtwain.TwainSource.setShowProgressBar(TwainSource.java:275)
	at free.lucifer.jtwain.scan.Source.setupSource(Source.java:111)
	at free.lucifer.jtwain.scan.Source.update(Source.java:100)
	at free.lucifer.jtwain.TwainScanner.fireListenerUpdate(TwainScanner.java:165)
	at free.lucifer.jtwain.TwainScanner.negotiateCapabilities(TwainScanner.java:113)
	at free.lucifer.jtwain.Twain.negotiateCapabilities(Twain.java:1067)
	at free.lucifer.jtwain.TwainSource.enable(TwainSource.java:334)
	at free.lucifer.jtwain.Twain.execute(Twain.java:1227)
	at free.lucifer.jtwain.TwainWndProc.callback(TwainWndProc.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeLong(Native Method)
	at com.sun.jna.Function.invoke(Function.java:421)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at jdk.proxy2/jdk.proxy2.$Proxy260.DispatchMessage(Unknown Source)
	at free.lucifer.jtwain.Twain$1.run(Twain.java:907)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by DenisLAD** [comment]
Try to check. Did some fix NPE error
#5

**Comment by DenisLAD** [comment]
No activity
